# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Uncloud < Formula
  desc "Uncloud CLI"
  homepage "https://uncloud.run"
  version "0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/psviderski/uncloud/releases/download/v0.2/uncloud_macos_amd64.tar.gz"
      sha256 "ad662ea53554cd22c25257b96308e4db6a97c452f97cf29d6fc95e6933b154c8"

      def install
        bin.install "uncloud"
        bin.install_symlink "uncloud" => "uc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/psviderski/uncloud/releases/download/v0.2/uncloud_macos_arm64.tar.gz"
      sha256 "b1cdc79beade97bb7616550cb3929e9e7635521a23ac5b11647ca7d0ea4f5ea4"

      def install
        bin.install "uncloud"
        bin.install_symlink "uncloud" => "uc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/psviderski/uncloud/releases/download/v0.2/uncloud_linux_amd64.tar.gz"
        sha256 "361eb4d4ff00a9d8129ebd91684e3de59ef32d16862f897337a5e2cee56cfe6a"

        def install
          bin.install "uncloud"
          bin.install_symlink "uncloud" => "uc"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/psviderski/uncloud/releases/download/v0.2/uncloud_linux_arm64.tar.gz"
        sha256 "7b0abe6071efb4413b9a55b0924063eaf5c73abea099cb43f0a16e19460acced"

        def install
          bin.install "uncloud"
          bin.install_symlink "uncloud" => "uc"
        end
      end
    end
  end
end
