# This file was generated by GoReleaser. DO NOT EDIT.
cask "docker-pussh" do
  desc "Upload Docker images to remote servers via SSH without an external registry."
  homepage "https://github.com/psviderski/unregistry"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "docker-pussh"

  on_macos do
    on_intel do
      url "https://github.com/psviderski/unregistry/releases/download/v0.2.0/unregistry_0.2.0_darwin_amd64.tar.gz"
      sha256 "eac409aac7ca9645ae55f8e05a8b653e8e81d3d542034b436dc7f583f8386a6e"
    end
    on_arm do
      url "https://github.com/psviderski/unregistry/releases/download/v0.2.0/unregistry_0.2.0_darwin_arm64.tar.gz"
      sha256 "eac409aac7ca9645ae55f8e05a8b653e8e81d3d542034b436dc7f583f8386a6e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/psviderski/unregistry/releases/download/v0.2.0/unregistry_0.2.0_linux_amd64.tar.gz"
      sha256 "eac409aac7ca9645ae55f8e05a8b653e8e81d3d542034b436dc7f583f8386a6e"
    end
    on_arm do
      url "https://github.com/psviderski/unregistry/releases/download/v0.2.0/unregistry_0.2.0_linux_arm64.tar.gz"
      sha256 "eac409aac7ca9645ae55f8e05a8b653e8e81d3d542034b436dc7f583f8386a6e"
    end
  end

  name "docker-pussh"

  caveats do
    <<~EOS
      To use docker-pussh as a Docker CLI plugin ('docker pussh' command) you need to create a symlink:

        mkdir -p ~/.docker/cli-plugins
        ln -sf #{HOMEBREW_PREFIX}/bin/docker-pussh ~/.docker/cli-plugins/docker-pussh

      After installation, you can use it with:
        docker pussh [OPTIONS] IMAGE[:TAG] [USER@]HOST[:PORT]

      To uninstall the plugin:
        rm ~/.docker/cli-plugins/docker-pussh
    EOS
  end

  # No zap stanza required
end
