# This file was generated by GoReleaser. DO NOT EDIT.
cask "docker-pussh" do
  desc "Upload Docker images to remote servers via SSH without an external registry."
  homepage "https://github.com/psviderski/unregistry"
  version "0.2.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "docker-pussh"

  on_macos do
    on_intel do
      url "https://github.com/psviderski/unregistry/releases/download/v0.2.1/unregistry_0.2.1_darwin_amd64.tar.gz"
      sha256 "1a4df9882a05dedaadf1e7e5cce93014e425744227ee9ef124ce8f43c85b96ed"
    end
    on_arm do
      url "https://github.com/psviderski/unregistry/releases/download/v0.2.1/unregistry_0.2.1_darwin_arm64.tar.gz"
      sha256 "1a4df9882a05dedaadf1e7e5cce93014e425744227ee9ef124ce8f43c85b96ed"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/psviderski/unregistry/releases/download/v0.2.1/unregistry_0.2.1_linux_amd64.tar.gz"
      sha256 "1a4df9882a05dedaadf1e7e5cce93014e425744227ee9ef124ce8f43c85b96ed"
    end
    on_arm do
      url "https://github.com/psviderski/unregistry/releases/download/v0.2.1/unregistry_0.2.1_linux_arm64.tar.gz"
      sha256 "1a4df9882a05dedaadf1e7e5cce93014e425744227ee9ef124ce8f43c85b96ed"
    end
  end

  name "docker-pussh"

  caveats do
    <<~EOS
      To use docker-pussh as a Docker CLI plugin ('docker pussh' command) you need to create a symlink:

        mkdir -p ~/.docker/cli-plugins
        ln -sf #{HOMEBREW_PREFIX}/bin/docker-pussh ~/.docker/cli-plugins/docker-pussh

      After installation, you can use it with:
        docker pussh [OPTIONS] IMAGE[:TAG] [USER@]HOST[:PORT]

      To uninstall the plugin:
        rm ~/.docker/cli-plugins/docker-pussh
    EOS
  end

  # No zap stanza required
end
