# This file was generated by GoReleaser. DO NOT EDIT.
cask "docker-pussh" do
  name "docker-pussh"

  caveats do
    <<~EOS
      To use docker-pussh as a Docker CLI plugin ('docker pussh' command) you need to create a symlink:

        mkdir -p ~/.docker/cli-plugins
        ln -sf #{HOMEBREW_PREFIX}/bin/docker-pussh ~/.docker/cli-plugins/docker-pussh

      After installation, you can use it with:
        docker pussh [OPTIONS] IMAGE[:TAG] [USER@]HOST[:PORT]

      To uninstall the plugin:
        rm ~/.docker/cli-plugins/docker-pussh
    EOS
  end

  name "docker-pussh"
  desc "Upload Docker images to remote servers via SSH without an external registry."
  homepage "https://github.com/psviderski/unregistry"
  version "0.4.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "docker-pussh"

  on_macos do
    on_intel do
      url "https://github.com/psviderski/unregistry/releases/download/v#{version}/unregistry_#{version}_darwin_amd64.tar.gz"
      sha256 "093d827016612b99be4554724be7793a7209d6978e3dbc6899d130b17d6d0a11"
    end
    on_arm do
      url "https://github.com/psviderski/unregistry/releases/download/v#{version}/unregistry_#{version}_darwin_arm64.tar.gz"
      sha256 "093d827016612b99be4554724be7793a7209d6978e3dbc6899d130b17d6d0a11"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/psviderski/unregistry/releases/download/v#{version}/unregistry_#{version}_linux_amd64.tar.gz"
      sha256 "093d827016612b99be4554724be7793a7209d6978e3dbc6899d130b17d6d0a11"
    end
    on_arm do
      url "https://github.com/psviderski/unregistry/releases/download/v#{version}/unregistry_#{version}_linux_arm64.tar.gz"
      sha256 "093d827016612b99be4554724be7793a7209d6978e3dbc6899d130b17d6d0a11"
    end
  end

  # No zap stanza required
end
